### ISSUE TITLE
Create a duty roster for issue triage

### ISSUE THREAD

**Issue by nrc** [tikv/sig-transaction#10]
We should have somebody on duty to do initial triage of issues. These are helpfully posted to slack once per day (I think). They could also triage new PRs to make sure they get review 

As well as a list of names, we should specify the work the person on duty should do.

**Comment by nrc** [comment]
cc @jackysp @andylokandy do either of you have thoughts on issue/PR triage?

**Comment by jackysp** [comment]
How about having the convener of the weekly meeting triage new PRs/issues? Next week should be @tiancaiamao. 
- [ ] @jackysp 
- [ ] @nrc 
- [ ] @MyonKeminta 
- [ ] @youjiali1995 
- [ ] @coocood 
- [ ] @tiancaiamao 
- [ ] @lysu 
- [ ] @imtbkcat 
- [ ] @cfzjywxk 
- [ ] @bobotu 
- [ ] @sticnarf 
- [ ] @andylokandy 
- [ ] @ekexium 
- [ ] @longfangsong 
- [ ] @you06
