### ISSUE TITLE
[PROPOSAL] sig-transaction integrates GitHub Discussion and moves stuff

### ISSUE THREAD

**Issue by tisonkun** [tikv/sig-transaction#108]
With an offline discussion with @andylokandy yesterday, I learned we create tikv/sig-transaction for collecting stuff and hosting a repository for design discussion.

However, the design document should have been put under [tikv/rfcs](https://github.com/tikv/rfcs), as well as we have GitHub Discussion for open-ended discussion.

@andylokandy @sticnarf and I reached a consensus that we turn on GitHub Discussion on [tikv/tikv](https://github.com/tikv/tikv) and moving disuccsion there under a category named `transaction`. Also we finalize the design document stuff under [tikv/rfcs](https://github.com/tikv/rfcs).

What do you think?

**Comment by tisonkun** [comment]
Still I found several questions, which are almost about "what to do with existing stuff". The whole idea would be archived this repository because we don't want to break any links already to this repository. And migrate stuff on demand.

1. For weekly meeting, we can easily move to the new category of GitHub Discussion, for upcoming people comment.
2. For design document, I'd like to copy them under [this directory](https://github.com/tikv/rfcs/tree/master/text) and with one more level directory `/transaction` if you want to.
3. For the website, it could be the most tricky part. I highly appreciate @nrc for the document site but it seems we have few stuff so far. I'd prefer we setup a knowledge base for tikv the whole concept and add design document as its submodule or show the link to design docs. To sum up, we hold the current document site and replace it with rich stuff later.

**Comment by nrc** [comment]
> However, the design document should have been put under tikv/rfcs

I'm not sure that this is true, since these are evolving design docs, not RFCs. The problem with moving to the RFC repo, is there is still a need to do early stage, informal design, and if we don't do that here then it will end up in a google doc, or on a whiteboard, both of which are less accessible

> we turn on GitHub Discussion on tikv/tikv

have we trialed GH discussions? I'm hesitant to move to something new and untested

> For weekly meeting, we can easily move to the new category of GitHub Discussion, for upcoming people comment.

Are these easily discoverable? The goal with having such minutes is so that interested community folk can see how decisions are made and how things evolve. That means there must be a discoverable, permanent record.

**Comment by tisonkun** [comment]
Thanks for your reply @nrc . Comment inline.

> I'm not sure that this is true, since these are evolving design docs, not RFCs. The problem with moving to the RFC repo, is there is still a need to do early stage, informal design, and if we don't do that here then it will end up in a google doc, or on a whiteboard, both of which are less accessible

Do you have a plan that design finalize under this repository finalized in tikv/rfcs? In another perspective, we don't implement code without a discussed design. I think it is ok to update rfc reflecting design changed if necessary. But async commit even a GA feature with this statement is still under discussion, which sounds weird. BTW I agree that for visibility a gdoc is not a good idea.

> > we turn on GitHub Discussion on tikv/tikv
> 
> have we trialed GH discussions? I'm hesitant to move to something new and untested

It is used by some projects. For example,

- https://github.com/jni-rs/jni-rs/discussions
- https://github.com/ti-community-infra/rfcs/discussions

But yes, it is new. My understanding is that for mature community they have their way for pre-RFC discussion, e.g. rust has [its forum](https://github.com/rust-lang/rfcs/blame/master/README.md#L92) and ASF projects have mailing list. We do not have one yet and open-ended discussion provided by GH Discussion is one way closed to our codebase.

If you find it comfortable, we can setup categories under tikv/tikv as 

```
- General
- Question
- PreRFC
```

or if @andylokandy & you as well as other transaction stuff think it is a significant different for transaction, as

```
- General
- Question
- Transaction
```

I think it is more discoverable with the trending of tikv/tikv project and provides similar experience for you guys in the core them to discuss features. 

> > For weekly meeting, we can easily move to the new category of GitHub Discussion, for upcoming people comment.
> 
> Are these easily discoverable? The goal with having such minutes is so that interested community folk can see how decisions are made and how things evolve. That means there must be a discoverable, permanent record.

As mentioned above, it could be more discoverable with the trending of tikv/tikv project as well as permanent recorded. Thanks for your effort to make community folks easy to catch up how decisions are made and how things evolve.

I agree that the data of discussion is held by GitHub but so do issues & prs, and thus recommend you keep a local copy if you don't trust GitHub for data keeping.

**Comment by andylokandy** [comment]
> Are these easily discoverable? The goal with having such minutes is so that interested community folk can see how decisions are made and how things evolve. That means there must be a discoverable, permanent record.

May I have a suggestion: make a pinned discussion (if GitHub can) under the transaction tab in Github Discussion, for gathering all links to individual meeting posts. 

Yet another problem is how to suggest changes to the meeting record. Can everyone that has permission edit the comment in GitHub discussion? @tisonkun

**Comment by tisonkun** [comment]
> May I have a suggestion: make a pinned discussion (if GitHub can) under the transaction tab in Github Discussion, for gathering all links to individual meeting posts.

Yes it can be done with [this approach](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions-in-your-repository#pinning-a-discussion).

> Yet another problem is how to suggest changes to the meeting record. Can everyone that has permission edit the comment in GitHub discussion? @tisonkun

Nope. Only the author of comment or someone who has the write privilege to for the repository can edit, according to [this document](https://docs.github.com/en/github/site-policy/github-community-guidelines#what-if-something-or-someone-offends-you).

The most difference between GH Discussion and Pull Request is that, as you using Gist, you can only quote reply but not comment in place, which acts more like a forum instead of collaborative document.

**Comment by tisonkun** [comment]
Hi @andylokandy @nrc @sticnarf  , now we have [a forum](https://internals.tidb.io/) for technical discussion about TiDB projects, and I'm glad to invite you to hold a `transaction` category for discussion about distributed transaction. If you are interested on it, please reply and I will set the category for you.

**Comment by tisonkun** [comment]
https://internals.tidb.io/t/category-request-transaction/60 and here is a category request for transaction.
