### ISSUE TITLE
Sync of PD timestamps and timestamps computed when resolving a lock for parallel commit

### ISSUE THREAD

**Issue by nrc** [tikv/sig-transaction#21]
@MyonKeminta believes there will be problems if and only if the computed ts is > PD's latest ts + 1. I'm not clear on the concrete problems this causes or if/how they can be mitigated.

**Comment by nrc** [comment]
This is not a problem if we only use timestamps from PD as read ts, but might be a problem due to `conflict_for_update_ts`.

**Comment by sticnarf** [comment]
A simple workaround is recording whether a timestamp is allocated from PD or calculated. We can limit deriving a timestamp from a calculated timestamp.
In other words, if `conflict_for_update_ts` is a calculated timestamp, TiDB gets a new timestamp from PD and retry reading.

**Comment by MyonKeminta** [comment]
@sticnarf I think we do not have any other better solution. We can adopt this solution for now, and in the scenario you said maybe it's better to disable parallel commit.

**Comment by youjiali1995** [comment]
Agree.

**Comment by nrc** [comment]
This is currently not a bug in the implementation, but is something we should bear in mind for future optimisations.
