### ISSUE TITLE
Compatibility between async commit fallback and CDC

### ISSUE THREAD

**Issue by sticnarf** [tikv/sig-transaction#79]
If we fallback from async commit using the solution 2 in https://github.com/tikv/sig-transaction/issues/64, we need to amend the primary lock clearing the async commit mark. Then, there can be two mutations writing the same lock. I am not sure whether CDC can handle this case.

**Comment by sticnarf** [comment]
cc @5kbpers @MyonKeminta

**Comment by youjiali1995** [comment]
We write the same lock when refreshes TTL too. I think CDC can handle it.

**Comment by sticnarf** [comment]
I write a new design of implementing fallback. It does not rewrite the primary lock (it's actually unnecessary, I think).
