### ISSUE TITLE
CDC and TiFlash can't handle the case that records in write cf is rewritten

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/sig-transaction#81]
It's found that currently CDC and TiFlash is still not fully compatible with async commit, in case the commit record is rewritten because of overlapping rollback.

**Comment by sticnarf** [comment]
Resolved by:
CDC: https://github.com/tikv/tikv/pull/9359 and https://github.com/tikv/tikv/pull/9446
TiFlash: https://github.com/pingcap/tics/pull/1278
