### ISSUE TITLE
Update TLA+ Spec for async commit

### ISSUE THREAD

**Issue by andylokandy** [tikv/sig-transaction#97]
The [TiKV](https://github.com/tikv/tikv) has recently been launching a new feature in the transaction model named [Async commit](https://github.com/tikv/sig-transaction/tree/master/design/async-commit). It's an optimization that reduces the commit latency from 2PC to 1PC. However, this feature has not been reflected in the [TLA+ Specs](https://github.com/pingcap/tla-plus/tree/master/DistributedTransaction).

This issue tracks updating the spec and also running TLC model checker on the new model to gain more confidence on the async commit design.

**Comment by zhuo1angT** [comment]
Hi @andylokandy, I'm interested in this project, and I'd like to take part in the GSoC 2021. What I can do to start?

**Comment by WT-Liu** [comment]
> Hi @andylokandy, I'm interested in this project, and I'd like to take part in the GSoC 2021. What I can do to start?

Hi @zhuo1angT Thanks for your interest! The students application of GSoC 2021 will be open on Mar 30. Stay tuned please!

**Comment by andylokandy** [comment]
This issue is now tracked by https://github.com/tikv/tikv/issues/10319
